apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-2
  labels:
    app: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
  - name: elasticsearchtransport
    port: 9300
    protocol: TCP
  selector:
    role: elasticsearch-2
