apiVersion: v1
kind: DeploymentConfig
metadata:
  name: elasticsearch-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: elasticsearch-3
    spec:
      containers:
      - name: elasticsearch-3
        image: ahmed/elasticsearch:latest
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: cluster.name
          value: "3scale-cluster"
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-1.3scale.svc.cluster.local:9300,elasticsearch-2.3scale.svc.cluster.local:9300"
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
