apiVersion: v1
kind: DeploymentConfig
metadata:
  name: elasticsearch-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: elasticsearch-1
    spec:
      volumes:
      - name: es-data-1
        persistentVolumeClaim:
          claimName: elasticsearch-1
      containers:
      - name: elasticsearch-1
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data-1
        image: ahmed/elasticsearch:latest
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: cluster.name
          value: "3scale-cluster"
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-2.3scale.svc.cluster.local:9300,elasticsearch-3.3scale.svc.cluster.local:9300"
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
