apiVersion: v1
kind: DeploymentConfig
metadata:
  name: curator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: curator
    spec:
      containers:
      - name: curator
        image: ahmed/curator:latest
