apiVersion: v1
kind: DeploymentConfig
metadata:
  name: logstash-production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash-production
    spec:
      volumes:
      - configMap:
          defaultMode: 420
          name: logstash-production-conf
        name: logstash-production-conf
      - configMap:
          defaultMode: 420
          name: logstash-production-yml
        name: logstash-production-yml
      containers:
      - name: logstash-production
        volumeMounts:
        - mountPath: /usr/share/logstash/pipeline/logstash.conf
          name: logstash-production-conf
          subPath: logstash.conf
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-production-yml
          subPath: logstash.yml
      image: docker.elastic.co/logstash/logstash:6.5.1
        ports:
        - containerPort: 1601
          protocol: UDP
