apiVersion: v1
kind: Service
metadata:
  name: logstash-staging
  labels:
    app: logstash-staging
spec:
  ports:
  - name: logstash-staging
    port: 1601
    protocol: UDP
  selector:
    app: logstash-staging
