apiVersion: v1
kind: Service
metadata:
  name: logstash-production
  labels:
    app: logstash-production
spec:
  ports:
  - name: logstash-production
    port: 1601
    protocol: UDP
  selector:
    app: logstash-production
